"""empty message

Revision ID: 14566cb3ec6d
Revises: 4dbb7ec4a2e1
Create Date: 2015-06-26 08:11:01.141507

"""

# revision identifiers, used by Alembic.
revision = '14566cb3ec6d'
down_revision = '4dbb7ec4a2e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('type', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'type')
    ### end Alembic commands ###
