"""empty message

Revision ID: 1a6c1271d037
Revises: 26fc5b76148e
Create Date: 2015-06-25 22:24:51.022734

"""

# revision identifiers, used by Alembic.
revision = '1a6c1271d037'
down_revision = '26fc5b76148e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zwave_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zway_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('device_type_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zway_id')
    )
    op.create_table('instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zway_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zway_id')
    )
    op.create_table('user2device',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('instance2command_group',
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('command_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['command_group_id'], ['command_group.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['instance.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance2command_group')
    op.drop_table('user2device')
    op.drop_table('instance')
    op.drop_table('device')
    op.drop_table('zwave_user')
    op.drop_table('device_type')
    op.drop_table('command_group')
    ### end Alembic commands ###
