"""empty message

Revision ID: 26fc5b76148e
Revises: 4ba1c0a75b27
Create Date: 2015-06-21 17:03:35.620883

"""

# revision identifiers, used by Alembic.
revision = '26fc5b76148e'
down_revision = '4ba1c0a75b27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('failed_logins', sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET active = True')
    op.execute('UPDATE "user" SET failed_logins = 0')
    op.alter_column('user', 'active', nullable=False)
    op.alter_column('user', 'failed_logins', nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'failed_logins')
    op.drop_column('user', 'active')
    ### end Alembic commands ###
