"""empty message

Revision ID: 40b216ac0715
Revises: dac0423c0e3
Create Date: 2015-07-04 13:51:16.326196

"""

# revision identifiers, used by Alembic.
revision = '40b216ac0715'
down_revision = 'dac0423c0e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command_group', sa.Column('zway_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'command_group', ['zway_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'command_group', type_='unique')
    op.drop_column('command_group', 'zway_id')
    ### end Alembic commands ###
