"""empty message

Revision ID: 4ba1c0a75b27
Revises: 4bd2467318bb
Create Date: 2015-06-21 11:44:13.246609

"""

# revision identifiers, used by Alembic.
revision = '4ba1c0a75b27'
down_revision = '4bd2467318bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bearer_token', sa.Column('last_active', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bearer_token', 'last_active')
    ### end Alembic commands ###
